
const data = {
    products: [
        {
            name: 'Free Shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Free Shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 70,
            brand: 'Polo',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Free Shirt',
            category: 'Shirts',
            image: '/images/pants2.jpg',
            price: 70,
            brand: 'Calvin Clain',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Free Shirt',
            category: 'Shirts',
            image: '/images/pants3.jpg',
            price: 70,
            brand: 'Zara',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Free Shirt',
            category: 'Shirts',
            image: '/images/pants2.jpg',
            price: 70,
            brand: 'Coach',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Free Shirt',
            category: 'Shirts',
            image: '/images/pants3.jpg',
            price: 70,
            brand: 'Michle Chorse',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
    ]
}
export default data;
